export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SESSION = "CREATE_USER_SESSION";
export const CREATE_USER_PROFILE = "CREATE_USER_PROFILE";
export const LOAD_ON_CREATE_USER = "LOAD_ON_CREATE_USER";
export const LOAD_ON_LOGIN_USER = "LOAD_ON_LOGIN_USER";
export const LOAD_ON_PROFILE_UPDATE = "LOAD_ON_PROFILE_UPDATE";
export const DELETE_USER_SESSION = "DELETE_USER_SESSION";
